### ISSUE TITLE
Installation Broken

### ISSUE THREAD

**Issue by tomhughesnice** [openzipkin/zipkin-ui#39]
I ran the installation commands on npm version 4.1.2
```
$ npm install --dev
$ npm install typescript -g
$ npm start
```
Everything looks good when I run the commands. But when I open in a web browser it all goes wrong. See the following error in the console window.
```
Unhandled Promise rejection: Template parse errors:
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" [ERROR ->]let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template ["): NgbHighlight@0:37
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" let-part [ERROR ->]let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template [ngIf]="!i"): NgbHighlight@0:46
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("rOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span>[ERROR ->]<ng-template [ngIf]="!isOdd">{{part}}</ng-template></ng-template>"): NgbHighlight@0:124
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template ngFor [ngForOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightC"): NgbHighlight@0:0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
"let-" is only supported on template elements. ("<ng-template ngFor [n……} Error: Template parse errors:
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" [ERROR ->]let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template ["): NgbHighlight@0:37
"let-" is only supported on template elements. ("<ng-template ngFor [ngForOf]="parts" let-part [ERROR ->]let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span><ng-template [ngIf]="!i"): NgbHighlight@0:46
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("rOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightClass}}">{{part}}</span>[ERROR ->]<ng-template [ngIf]="!isOdd">{{part}}</ng-template></ng-template>"): NgbHighlight@0:124
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ng-template ngFor [ngForOf]="parts" let-part let-isOdd="odd"><span *ngIf="isOdd" class="{{highlightC"): NgbHighlight@0:0
    at SyntaxError.ZoneAwareError (eval at <anonymous> (http://localhost:3000/polyfills.js:4062:1), <anonymous>:992:33)
    at SyntaxError.BaseError [as constructor] (eval at <anonymous> (http://localhost:3000/vendor.js:2877:1), <anonymous>:25:16)
    at new SyntaxError (eval at <anonymous> (http://localhost:3000/vendor.js:165:1), <anonymous>:162:16)
    at TemplateParser.parse (eval at <anonymous> (http://localhost:3000/vendor.js:582:1), <anonymous>:169:19)
    at JitCompiler._compileTemplate (eval at <anonymous> (http://localhost:3000/vendor.js:1740:1), <anonymous>:380:68)
    at eval (eval at <anonymous> (http://localhost:3000/vendor.js:1740:1), <anonymous>:263:62)
    at Set.forEach (native)
    at JitCompiler._compileComponents (eval at <anonymous> (http://localhost:3000/vendor.js:1740:1), <anonymous>:263:19)
    at createResult (eval at <anonymous> (http://localhost:3000/vendor.js:1740:1), <anonymous>:145:19)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:3000/polyfills.js:4062:1), <anonymous>:334:26)
    at Zone.run (eval at <anonymous> (http://localhost:3000/polyfills.js:4062:1), <anonymous>:126:43)
    at eval (eval at <anonymous> (http://localhost:3000/polyfills.js:4062:1), <anonymous>:713:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:3000/polyfills.js:4062:1), <anonymous>:367:31)
    at Zone.runTask (eval at <anonymous> (http://localhost:3000/polyfills.js:4062:1), <anonymous>:166:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:3000/polyfills.js:4062:1), <anonymous>:546:35)
consoleError @ zone.js?fad3:522
handleUnhandledRejection @ zone.js?fad3:527
_loop_1 @ zone.js?fad3:562
drainMicroTaskQueue @ zone.js?fad3:566
zone.js?fad3:524 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: Template parse errors:
"let-" is only supported on template ele……}
consoleError @ zone.js?fad3:524
handleUnhandledRejection @ zone.js?fad3:527
_loop_1 @ zone.js?fad3:562
drainMicroTaskQueue @ zone.js?fad3:566
```

**Comment by adriancole** [comment]
you are very likely going to need a more recent version of node. have you
tried installing via ./mvnw clean install? This pins the version of node
iirc

**Comment by bharat-p** [comment]
Updated node and npm, still same error.
```
$ node -v
v7.10.0
```
```
$ npm -v
4.5.0
```

**Comment by adriancole** [comment]
gitter is a better place for troubleshooting. issues are good when we have some code or docs to change. are you able to hop on gitter? It is better than spamming watchers https://gitter.im/openzipkin/zipkin
